site_name: Betty
site_description: My space on the internet.
site_author: Huynh Duong

theme:
  icon:
    logo: material/penguin
  favicon: images/favicon.png
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
plugins:
  - tags:
      tags_file: tags.md
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true

markdown_extensions:
  - meta
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
extra:
  analytics:
    provider: google
    property: G-B8XM7XBEP5
    feedback:
      title: How do you feel?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/betty2310
      name: Betty on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/betty2310
      name: Betty on Linkedin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_betty2310
      name: Betty on Twitter
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/betty2310
      name: Betty on Facebook
copyright: Copyright &copy; 2022 Huynh Duong - Betty2310
repo_url: https://github.com/betty2310/docs
repo_name: betty230/docs
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/feedback.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
      - Home: index.md
      - Tags: tags.md
  - Blog:
      - Blog/Chuyện con gấu.md
      - Blog/Niềm vui nhỏ.md
      - Blog/1 tuần trải nghiệm Hackintosh - Phần 2.md
      - Blog/1 tuần trải nghiệm Hackintosh - Phần 1.md
      - Blog/Lần đầu đi phỏng vấn.md
      - Blog/c và c++.md
      - Blog/pgAdmin4.md
      - Blog/cá tháng 4.md
      - Blog/buffer.md
      - Blog/docker.md
      - Blog/endian.md
  - Project:
      - Project/index.md
      - Fomatem:
          - Project/fomatem/29jun.md
          - Project/fomatem/28jun.md
          - Project/fomatem/27jun.md
          - Project/fomatem/26jun.md
          - Project/fomatem/25jun.md
  - Learning:
      - Learning/index.md
  - About:
      - About/Me.md
