authors:
  betty:
    name: Huynh Duong
    description: Creator
    avatar: https://scontent.fhan2-4.fna.fbcdn.net/v/t1.6435-9/69078721_659851257846750_4222873572697178112_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=yr-LysPsV4QAX8USwfy&_nc_ht=scontent.fhan2-4.fna&oh=00_AfAIzEkB3_PeZO4JevHiLc-NjdAIs1nf7-48LV2TjIwXwg&oe=65232790